version: '3'
services:
  app:
    build: ./app
    container_name: my_website
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - app

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: >
      sh -c "certbot certonly --webroot --webroot-path=/var/www/certbot
             --email <your_email> --agree-tos --no-eff-email
             -d example.nl -d www.example.nl && nginx -s reload"


### This is a second Docker-container which will run along side Certbot. It'll updat the certificate automatically. ###
  cron:
    image: alpine:latest
    container_name: certbot-cron
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: >
      /bin/sh -c "echo '0 0,12 * * * root /opt/certbot/bin/python -c \"import random; import time; time.sleep(random.random() * 3600)\" && sudo certbot renew -q' > /etc/crontabs/root && crond -f"
    depends_on:
      - certbot